Repository chingu-voyage4/Bears-Team-20, pull requests merged in 2018-02, with the labels that each got.

#13 init
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/Login/Login.js
  client/src/components/Signup/Signup.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/registerServiceWorker.js
  server/.gitignore
  server/package.json
Labels: review

#21 Feature/precommit-hook-setup
  client/.eslintignore
  client/.eslintrc.js
  client/package.json
  client/src/App.js
  client/yarn.lock
Labels: enhancement

#24 ci-config
  .circleci/config.yml
Labels: enhancement

#26 fix/ci_working_dir_name
  .circleci/config.yml
Labels: bug

#27 fix/ci_path
  .circleci/config.yml
Labels: bug

#28 tweaked paths to get rid of redundancy
  .circleci/config.yml
Labels: bug

#29 fix/remove_general_line
  .circleci/config.yml
Labels: bug

#31 enhancement/configure-babel-server
  server/.babelrc
  server/app.js
  server/package.json
  server/yarn.lock
Labels: enhancement, review

#32 enhancement/configure-lint-and-husky
  server/app.js
  server/package.json
  server/yarn.lock
Labels: enhancement, review

#33 Feature/login frontend
  client/package.json
  client/src/actions/index.js
  client/src/actions/login.js
  client/src/actions/signup.js
  client/src/actions/user.js
  client/src/components/Login/Login.css
  client/src/components/Login/Login.js
  client/src/components/Login/Login.test.js
  client/src/components/Login/index.js
  client/src/index.js
  client/src/reducers/index.js
  client/src/reducers/login.js
  client/src/reducers/user.js
  client/src/sagas/index.js
  client/src/sagas/login.js
  client/src/sagas/signup.js
  client/src/store/configureStore.dev.js
  client/src/store/configureStore.prod.js
  client/yarn.lock
Labels: review
