Repository chingu-voyage4/Bears-Team-20, pull requests merged in 2018-03, with the labels that each got.

#36 fixed eslint problems
  client/.eslintignore
  client/package.json
  client/src/actions/login.js
  client/src/actions/signup.js
  client/src/actions/user.js
  client/src/components/Login/index.js
  client/src/reducers/index.js
  client/src/reducers/login.js
  client/src/reducers/user.js
  client/src/sagas/index.js
  client/src/sagas/login.js
  client/src/sagas/signup.js
  client/src/store/configureStore.dev.js
  client/src/store/configureStore.js
  client/src/store/configureStore.prod.js
  client/yarn.lock
Labels: bug, review

#37 Mongo Connection Error
  client/.eslintignore
  client/package.json
  client/src/actions/login.js
  client/src/actions/signup.js
  client/src/actions/user.js
  client/src/components/Login/index.js
  client/src/reducers/index.js
  client/src/reducers/login.js
  client/src/reducers/user.js
  client/src/sagas/index.js
  client/src/sagas/login.js
  client/src/sagas/signup.js
  client/src/store/configureStore.dev.js
  client/src/store/configureStore.js
  client/src/store/configureStore.prod.js
  client/yarn.lock
Labels: review

#40 feature-implemented-react-router
  client/package.json
  client/src/index.js
  client/src/sagas/index.js
  client/src/store/configureStore.js
  client/yarn.lock
Labels: enhancement, review

#39 Mongo connection error
  client/package-lock.json
  server/app.js
  server/auth-router.js
Labels: review

#42 Chore/backend dir structure
  server/.gitignore
  server/app.js
  server/auth-router.js
  server/middleware/search.js
  server/models/user.js
  server/package.json
  server/routes/auth.js
  server/yarn.lock
Labels: review

#44 Feature/search youtube
  server/app.js
  server/middleware/search.js
  server/middleware/search.test.js
  server/package.json
  server/routes/search.js
  server/yarn.lock
Labels: review

#45 Feature/search soundcloud
  server/middleware/search.js
  server/middleware/search.test.js
  server/package.json
  server/routes/search.js
  server/yarn.lock
Labels: review

#49 Feature/search frontend
  client/.gitignore
  client/package.json
  client/src/actions/search.js
  client/src/actions/search.test.js
  client/src/components/Search/Search.css
  client/src/components/Search/SearchInput/index.js
  client/src/components/Search/SearchResults/ResultItem.css
  client/src/components/Search/SearchResults/ResultItem.js
  client/src/components/Search/SearchResults/index.js
  client/src/components/Search/index.js
  client/src/reducers/index.js
  client/src/reducers/search.js
  client/src/reducers/search.test.js
  client/src/sagas/index.js
  client/src/sagas/search.js
  client/src/sagas/search.test.js
  client/yarn.lock
Labels: review

#54 feature/deezer-support
  server/middleware/search.js
  server/package.json
  server/yarn.lock
Labels: enhancement, review

#58 Feature/google auth
  client/package.json
  client/src/App.js
  client/src/actions/login.js
  client/src/actions/signup.js
  client/src/actions/user.js
  client/src/components/Login/Login.css
  client/src/components/Login/index.js
  client/src/components/Navbar/index.js
  client/src/components/Signup/index.js
  client/src/reducers/login.js
  client/src/reducers/signup.js
  client/src/reducers/user.js
  client/src/reducers/user.test.js
  client/src/sagas/index.js
  client/src/sagas/login.js
  client/src/sagas/signup.js
  client/src/sagas/user.js
  server/app.js
  server/middleware/passport.js
  server/models/user.js
  server/package.json
  server/routes/auth.js
  server/yarn.lock
Labels: review

#59 Feature/playlist
  server/models/playlist.js
  server/models/song.js
  server/models/user.js
Labels: review

#56 Feature/player frontend
  client/package.json
  client/src/App.js
  client/src/actions/player.js
  client/src/actions/player.test.js
  client/src/components/Music/Music.test.js
  client/src/components/Music/index.js
  client/src/components/Player/CurrentPlaylist/CurrentPlaylist.css
  client/src/components/Player/CurrentPlaylist/index.js
  client/src/components/Player/Player.css
  client/src/components/Player/index.js
  client/src/components/Search/Search.css
  client/src/components/Search/SearchInput/SearchInput.css
  client/src/components/Search/SearchInput/index.js
  client/src/components/Search/SearchResults/ResultItem.js
  client/src/components/Search/SearchResults/index.js
  client/src/components/Search/index.js
  client/src/reducers/index.js
  client/src/reducers/player.js
  client/src/reducers/player.test.js
  client/yarn.lock
Labels: review

#64 Feature/profile frontend
  README.md
  client/src/App.js
  client/src/actions/user.js
  client/src/actions/user.test.js
  client/src/components/Profile/ChangePassword/ChangePassword.css
  client/src/components/Profile/ChangePassword/index.js
  client/src/components/Profile/ChangePicture/ChangePicture.css
  client/src/components/Profile/ChangePicture/index.js
  client/src/components/Profile/Profile.css
  client/src/components/Profile/index.js
  client/src/reducers/user.js
  client/src/reducers/user.test.js
  client/src/sagas/user.js
  client/src/sagas/user.test.js
  server/middleware/passport.js
  server/models/playlist.js
  server/models/user.js
  server/routes/auth.js
Labels: review

#65 Feature/landing page
  README.md
  client/public/cell.png
  client/public/icons/music.png
  client/public/icons/soundcloud.png
  client/public/icons/spotify.png
  client/public/icons/vimeo.png
  client/public/icons/youtube.png
  client/src/App.css
  client/src/components/Landing/Landing.css
  client/src/components/Landing/Landing.test.js
  client/src/components/Landing/index.js
  client/src/components/Navbar/Navbar.css
Labels: review

#67 Feature/playlist routes
  client/src/components/Landing/index.js
  server/app.js
  server/middleware/auth.js
  server/models/playlist.js
  server/models/song.js
  server/models/user.js
  server/routes/playlist.js
Labels: review
